"""
Gmail email service.

Mirrors the credential management pattern from ~/calendar_bot/common/credentials.py:
  - Token files live at GOOGLE_AUTH_PATH/token_{email_suffix}.json
  - Tokens are auto-refreshed when expired
  - Initial tokens are generated by scripts/generate_gmail_token.py

Gmail scope required: https://www.googleapis.com/auth/gmail.send
"""
import base64
import logging
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from pathlib import Path
from urllib.parse import urlencode

from google.auth.exceptions import RefreshError
from google.auth.transport.requests import Request
from google.oauth2.credentials import Credentials
from googleapiclient.discovery import build

from config import get_settings

logger = logging.getLogger(__name__)

SCOPES = ["https://www.googleapis.com/auth/gmail.send"]


# ── Credential management (identical pattern to calendar_bot) ─────────────────

def _load_credentials() -> Credentials:
    """
    Load Gmail OAuth credentials from disk, auto-refreshing if expired.
    Token path: GOOGLE_AUTH_PATH/token_{suffix}.json
    where suffix is everything before @ in SENDER_EMAIL.
    """
    settings = get_settings()
    sender = settings.sender_email
    if not sender:
        raise RuntimeError("SENDER_EMAIL is not configured.")

    suffix = sender.split("@")[0]
    token_path = Path(settings.google_auth_path) / f"token_{suffix}.json"

    if not token_path.exists():
        raise FileNotFoundError(
            f"Gmail token not found at {token_path}. "
            "Run backend/scripts/generate_gmail_token.py to authorise."
        )

    creds = Credentials.from_authorized_user_file(str(token_path), SCOPES)

    if creds.expired and creds.refresh_token:
        logger.info("Gmail token expired — refreshing...")
        try:
            creds.refresh(Request())
            token_path.write_text(creds.to_json())
            logger.info("Gmail token refreshed and saved.")
        except RefreshError as exc:
            logger.error("Gmail refresh token is invalid. Re-run generate_gmail_token.py")
            raise

    return creds


def _gmail_service():
    return build("gmail", "v1", credentials=_load_credentials())


def _send(to: str, subject: str, html_body: str) -> None:
    """Low-level send via Gmail API."""
    settings = get_settings()
    sender = settings.sender_email

    msg = MIMEMultipart("alternative")
    msg["to"] = to
    msg["from"] = sender
    msg["subject"] = subject
    msg.attach(MIMEText(html_body, "html"))

    raw = base64.urlsafe_b64encode(msg.as_bytes()).decode()
    _gmail_service().users().messages().send(
        userId="me", body={"raw": raw}
    ).execute()

    logger.info("Email sent to %s | subject: %s", to, subject)


# ── Email templates ───────────────────────────────────────────────────────────

def send_welcome_email(to_email: str, user_name: str) -> None:
    """
    Onboarding email sent on registration.
    Replicates the 'Ironskillet Registration Welcome Email' n8n workflow.
    """
    settings = get_settings()
    prefs_url = f"{settings.app_base_url}/settings"

    html = f"""
    <!DOCTYPE html>
    <html>
    <head><meta charset="utf-8"></head>
    <body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
                 background:#f9f9f9; margin:0; padding:40px 20px;">
      <div style="max-width:560px; margin:0 auto; background:#fff;
                  border-radius:12px; overflow:hidden; box-shadow:0 2px 8px rgba(0,0,0,.08);">

        <div style="background:#1a1a2e; padding:32px; text-align:center;">
          <h1 style="color:#e2b96f; margin:0; font-size:28px; letter-spacing:1px;">
            🍽️ Iron Skillet
          </h1>
          <p style="color:#aaa; margin:8px 0 0; font-size:14px;">
            Your personal AI-powered recipe vault
          </p>
        </div>

        <div style="padding:32px;">
          <h2 style="color:#1a1a2e; margin-top:0;">
            Welcome, {user_name}! 👋
          </h2>
          <p style="color:#444; line-height:1.6;">
            You're all set up. Here's how to get the most out of Iron Skillet:
          </p>

          <ol style="color:#444; line-height:2;">
            <li><strong>Add recipes</strong> — paste a URL or type your own</li>
            <li><strong>Set your dietary preferences</strong> — so the AI knows what to suggest</li>
            <li><strong>Connect Todoist</strong> — to sync ingredient shopping lists automatically</li>
            <li><strong>Use Instant Chef</strong> — get AI meal ideas, click one, and the recipe is
                scraped and saved for you</li>
          </ol>

          <h3 style="color:#1a1a2e;">Connecting Todoist (optional)</h3>
          <p style="color:#444; line-height:1.6;">
            To enable automatic grocery list syncing:
          </p>
          <ol style="color:#444; line-height:2;">
            <li>Go to <a href="https://todoist.com/app/settings/integrations/developer"
                style="color:#e2b96f;">Todoist → Settings → Integrations → Developer</a></li>
            <li>Copy your <strong>API token</strong></li>
            <li>Paste it in your <a href="{prefs_url}" style="color:#e2b96f;">Preferences page</a></li>
          </ol>

          <div style="text-align:center; margin-top:32px;">
            <a href="{prefs_url}"
               style="background:#e2b96f; color:#1a1a2e; padding:14px 28px;
                      border-radius:8px; text-decoration:none; font-weight:700;
                      display:inline-block;">
              Set Up Preferences →
            </a>
          </div>
        </div>

        <div style="padding:16px 32px; background:#f5f5f5; text-align:center;
                    color:#999; font-size:12px;">
          Iron Skillet · Self-hosted meal planning
        </div>
      </div>
    </body>
    </html>
    """

    _send(to_email, "Welcome to Iron Skillet 🍳", html)


def send_meal_plan_email(
    to_email: str,
    user_name: str,
    user_id: int,
    recipes: list[dict],
    select_token: str,
) -> None:
    """
    Weekly meal plan email with recipe cards and 'Select This' action links.
    Replicates the 'Ironskillet' n8n workflow email output.

    Each recipe dict: {"title": str, "url": str, "description": str, "is_favorite": bool}
    select_token: HMAC-signed token for this user (from services/chef.py) embedded in links.
    """
    settings = get_settings()

    def recipe_card(r: dict) -> str:
        badge = (
            '<span style="background:#e2b96f;color:#1a1a2e;padding:3px 8px;'
            'border-radius:4px;font-size:11px;font-weight:700;">⭐ Favourite</span>'
            if r.get("is_favorite")
            else '<span style="background:#4a90d9;color:#fff;padding:3px 8px;'
            'border-radius:4px;font-size:11px;font-weight:700;">🤖 AI Pick</span>'
        )
        params = urlencode({
            "token": select_token,
            "title": r["title"],
            "url": r.get("url", ""),
        })
        select_url = f"{settings.app_base_url}/api/chef/select-from-email?{params}"

        return f"""
        <div style="border:1px solid #eee; border-radius:10px; padding:20px;
                    margin-bottom:16px; background:#fff;">
          <div style="display:flex; justify-content:space-between; align-items:flex-start;">
            <h3 style="margin:0 0 6px; color:#1a1a2e; font-size:17px;">{r['title']}</h3>
            {badge}
          </div>
          <p style="color:#666; margin:8px 0 12px; font-size:14px; line-height:1.5;">
            {r.get('description', '')}
          </p>
          {'<a href="' + r["url"] + '" style="color:#999;font-size:12px;">View source</a>' if r.get("url") else ''}
          <div style="margin-top:14px;">
            <a href="{select_url}"
               style="background:#1a1a2e; color:#e2b96f; padding:10px 20px;
                      border-radius:6px; text-decoration:none; font-weight:700;
                      font-size:14px; display:inline-block;">
              Add to My Recipes →
            </a>
          </div>
        </div>
        """

    cards_html = "".join(recipe_card(r) for r in recipes)

    html = f"""
    <!DOCTYPE html>
    <html>
    <head><meta charset="utf-8"></head>
    <body style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;
                 background:#f9f9f9;margin:0;padding:40px 20px;">
      <div style="max-width:600px;margin:0 auto;background:#fff;
                  border-radius:12px;overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,.08);">

        <div style="background:#1a1a2e;padding:28px 32px;text-align:center;">
          <h1 style="color:#e2b96f;margin:0;font-size:26px;">🍽️ Your Meal Plan</h1>
          <p style="color:#aaa;margin:6px 0 0;font-size:14px;">
            Curated just for you, {user_name}
          </p>
        </div>

        <div style="padding:28px 32px;">
          <p style="color:#444;margin:0 0 20px;line-height:1.6;">
            Here are this week's meal ideas based on your preferences.
            Click <strong>Add to My Recipes</strong> on any card to save it and
            automatically sync the ingredients to your Todoist grocery list.
          </p>

          {cards_html}
        </div>

        <div style="padding:16px 32px;background:#f5f5f5;text-align:center;
                    color:#999;font-size:12px;">
          Iron Skillet · Self-hosted meal planning
        </div>
      </div>
    </body>
    </html>
    """

    _send(to_email, "🍽️ Your Weekly Meal Ideas — Iron Skillet", html)
